language: java
before_script:
  - mysql -e 'create database copyit;'
  - mysql copyit < database.sql
  - mysql copyit < test/test.sql
script:
  - mvn test -DtestConfigFile=test/travis.config
jdk:
  - oraclejdk7
  - openjdk7
notifications:
  irc:
    channels:
      - "irc.freenode.org#copyit"
    on_success: change
    on_failure: always
  email:
    on_success: never
    on_failure: always
