language: java
script:
 - mvn test
jdk:
 - oraclejdk7
 - openjdk7
notifications:
  irc:
    channels:
      - "irc.freenode.org#copyit"
    on_success: change
    on_failure: always
  email:
    on_success: never
    on_failure: always
